package com.base.common.utils

enum class RamsIntEnums(var value:Int){
    DEFAULT_VALUE(-1),
    FIXED_UNIT_TYPE_ID(2),
    REMOVED_UNIT_STATUS_ID(1),
    IN_OPERATION_ENF_STATUS_ID(3),
    UNDER_MAINTENANCE(2),
    MALFUNCTIONING(4),
    SPEED_ENFORCEMENT_FUNCTION_ID(4),
    ALL_PRIORITIES(0),
    NORMAL_PRIORITIES(1),
    HIGH_PRIORITIES(2),
    URGENT_PRIORITIES(3),

    TICKETS_NEW(1),
    TICKETS_REVIEW_ISSUE(2),
    TICKETS_REVIEWED(3),
    TICKETS_ASSIGN_ENGINEER(4),
    TICKETS_MAINTENANCE_PLAN(5),
    TICKETS_MAINTENANCE_STARTED(6),
    TICKETS_MAINTENANCE_REVIEWED(8),
    TICKETS_MAINTENANCE_CLOSED(7),


    MAINTENANCE_BASED_ON_TICKET_ID(3),

    REVIEW_PLAN_ADP_PM(2),
    REVIEW_PLAN_MAINTENANCE_PM(1),


    ADP_SPARE_PART_ITEM(1),
    VENDOR_SPARE_PART_ITEM(2),

    READY_FOR_EXECUTION(1),
    REVIEW_SUPERVISOR(2),
    REVIEW_ADP_PM(3),
    REVIEW_ENGINEER(4),
    ALL_ENFORCEMENT_UNIT_PRIORITY_STATUS(1),

    POLICE_VISIT_CREATE_INSPECTION_REPORT(1),
    POLICE_VISIT_VIEW_INSPECTION_REPORT(2),


    CORRECTIVE_MAINTENANCE(2),
    PREVENTIVE_MAINTENANCE(1),
    MAINTENANCE_BASED_ON_TICKET(3),

    RADAR_PART_HAVE_ISSUE(6),


    MAINTENANCE_TASK_REVIEW_ENGINEER(4),
    MAINTENANCE_TASK_CLOSED(5),





}

enum class RamsStringEnums(var value:String){
    DEFAULT_VALUE(""),
    ENF_UNIT_ID_TO_VIEW_DETAILS("enfIdForDetails"),
    ENF_UNIT_ID_TO_EDIT_DETAILS("enfIdForEdit"),
    WHICH_POLICE_VISIT_SCREEN("whichPoliceVisit"),
    ENF_UNIT("enfUnit")
}